/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn foo() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn add(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
